Bugfix and reimplement Pictrs
YunoHost-Apps/lemmy_ynh pull request #76
Opened 2023-12-23 21:23 UTC by Gildas-GH

## Problem

The current package in master has three problems : 

- It is not up to date with upstream
- It is broken due to an error with Sharp
- It doesn't support image upload

## Solution

- The first problem cannot be solved as the PostgreSQL version available in Bullseye doesn't meet the requirements of Lemmy. We have to wait.
- The two other can be solved with #43 and a bugfix contained in this branch

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-12-23 21:59 UTC, ericgaspar commented
!testme

2023-12-24 07:56 UTC, ericgaspar requested changes

2023-12-24 07:56 UTC, ericgaspar commented on scripts/change_url
> +ynh_systemd_action --service_name=$app --action="stop" --line_match="Stopped" "/var/log/$app/$app.log"
```suggestion
ynh_systemd_action --service_name=$app --action="stop" --line_match="Stopped" --log_path="/var/log/$app/$app.log"
```

2023-12-24 07:56 UTC, ericgaspar commented on manifest.toml
> +    packages = "postgresql espeak rsync libfuse2 libimage-exiftool-perl ffmpeg"
```suggestion
    packages = "postgresql, espeak, rsync, libfuse2, libimage-exiftool-perl, ffmpeg"
```

2023-12-24 07:56 UTC, ericgaspar commented on scripts/change_url
> +ynh_systemd_action --service_name=$app --action="stop" --line_match="Stopped" "/var/log/$app/$app.log"
log_path are set to differently in upgrade script `--log_path=systemd`

2023-12-24 13:30 UTC, Gildas-GH commented on scripts/change_url
> +ynh_systemd_action --service_name=$app --action="stop" --line_match="Stopped" "/var/log/$app/$app.log"
What's the best practice ? Write logs in the file ?

2023-12-26 08:37 UTC, merged